### PR TITLE
Try turning teleproto into a wrapper around chimney

### PR DESCRIPTION
**Pull request by urmaul**
#### Has the version number been increased?
 - [ ] Yes! (or not but it was intended to not increase it)

### CODE REVIEW

**Comment by urmaul** [comment]
The idea was to use chimney macros instead of teleproto macros. Calling Transformer.derive is easy but it works only when chimney can derive all recursive transformers. If we override some conversions by providing implicit writers, chimney doesn't care. It needs transformers.
If we don't find a way to make chimney use writer overrides, we'll have to convert them into transformers in every repository. That's manageable but not a drop-in replacement.
I tried converting stuff. I managed to turn chimney transformers into teleproto writers but not vice versa (error covariant type P occurs in contravariant position...).
I'll look more into it but so far by best idea is to teach teleproto use chimney transformers as overrides when they are available. Then we can convert our app-specific writers one by one and when all of them are converted... Dunno.

**Comment by urmaul** [comment]
To make it nicer we need something like:

```
trait Writer[M, P] extends Transformer[M, P]
```

but in this case you can't have covariant/contravariant type parameters for `Writer`. And in this case, `VersionedModelWriter` doesn't compile because ot has a map of writers to different types...

**Comment by MateuszKubuszok** [comment]
I'd say if you want to offload things to Chimney, while keep an easy way to add your own staff, it would be easier to just use the macros directly:

 * start building on top of:
   * https://github.com/scalalandio/chimney/blob/master/chimney/src/main/scala/io/scalaland/chimney/internal/compiletime/derivation/transformer/Derivation.scala
   * https://github.com/scalalandio/chimney/blob/master/chimney/src/main/scala-2/io/scalaland/chimney/internal/compiletime/derivation/transformer/DerivationPlatform.scala
   * https://github.com/scalalandio/chimney/blob/master/chimney/src/main/scala-3/io/scalaland/chimney/internal/compiletime/derivation/transformer/DerivationPlatform.scala
 * edit the `protected val rulesAvailableForPlatform: List[Rule]`
   * provide your own summoning to replace https://github.com/scalalandio/chimney/blob/master/chimney/src/main/scala/io/scalaland/chimney/internal/compiletime/derivation/transformer/rules/TransformImplicitRuleModule.scala
   * maybe add some additional rules for PB-specific stuff
 * replace https://github.com/scalalandio/chimney/blob/master/chimney/src/main/scala/io/scalaland/chimney/internal/compiletime/derivation/transformer/Gateway.scala with your own entrypoints

This way:

 * there would be no overhead for converting back and forth
 * your API would NOT rely on Transformers/PartialTransformers
 * you could inject your custom rules without fighting with variance, implicit priority, etc

It's pretty much doable, although it rely on undocumented internal APIs, so feel free to open a [discussion](https://github.com/scalalandio/chimney/discussions) if you want to try this approach.

**Comment by urmaul** [comment]
Closing it in favor of https://github.com/moia-oss/teleproto/pull/338

**Pull request closed without merging**
