### PR TITLE
Separate scala 2 and 3 code to allow for cross-compiling

### PR DESCRIPTION
**Pull request by willbinzi**
#### Has the version number been increased?
 - [ ] Yes! (or not but it was intended to not increase it)

### CODE REVIEW

**Review by saeltz — APPROVED** [review]
Nice!
Do you think we can keep the work-in-progress of the Scala 3 macro implementations in the respective files? Then we can easily continue and also merge my PRs into that.

**Comment by willbinzi** [comment]
>Do you think we can keep the work-in-progress of the Scala 3 macro implementations in the respective files? Then we can easily continue and also merge my PRs into that.
Yeah sounds good. Do you think it's worth keeping a base branch that compiles so we can make changes gradually or do you think it's not worth it? Would definitely understand an argument to say that the next step that actually compiles from here would probably be a whole macro working, at which point we've probably cracked the whole thing, but it might allow us to focus a bit more and test our first macro before moving on.

**Comment by saeltz** [comment]
> Do you think it's worth keeping a base branch that compiles so we can make changes gradually or do you think it's not worth it?

**Comment by saeltz** [comment]
> Do you think it's worth keeping a base branch that compiles so we can make changes gradually or do you think it's not worth it?

Honestly, I don't think we can finish the implementation in one PR. So the `scala3` branch will be failing for quite some time. But `master` will still compile.

**Pull request merged**
